language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 WP_TRAVISCI=grunt

before_script:
    - npm install
    - composer install

script:
    - grunt
