sudo: false
language: php

# Cache some data across builds for performance.
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_pull_requests: true
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS

branches:
  only:
    - master

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 WP_TRAVISCI=grunt

before_script:
    - npm install
    - composer install

script:
    - grunt
